"""Window → list of (filename, markdown_with_frontmatter) source documents.

Produces a small, high-signal set per window:

1. ONE ``<until>-changes.md`` — merged PRs + commit-volume digest.
   When ``repo_qualifier`` is set (multi-repo mode): ``<repo>-<until>-changes.md``.
2. UP TO ``max_modules`` ``module-<slug>-<until>.md`` files — snapshots of the
   top-level code directories most changed in the window.
   When ``repo_qualifier`` is set: ``module-<repo>-<slug>-<until>.md``.

**Single-repo** (``repo_qualifier=None``): filenames are unqualified — identical
to the historic behaviour, so existing ingested corpora are unaffected.

**Multi-repo** (``repo_qualifier`` provided): every filename and doc body carry
the repo identifier so wiki-weaver keeps pages from different repos distinct and
citations always point back to the right source.

Never fabricates provenance.  All data comes from git plumbing or the gh CLI.
"""

from __future__ import annotations

import re
import textwrap
from typing import Optional

from . import gitio

# Maximum number of files shown in a module inventory before truncating.
_MAX_INVENTORY_FILES = 60

# README filename candidates tried in order.
_README_CANDIDATES = [
    "README.md",
    "readme.md",
    "README.rst",
    "Readme.md",
    "docs/README.md",
]

# Maximum body chars shown per PR before truncating.
_PR_BODY_MAX = 600

# ---------------------------------------------------------------------------
# PR classification helpers  (ROUTINE vs SUBSTANTIVE)
# ---------------------------------------------------------------------------

# Any author login ending in [bot] is a bot (dependabot[bot], release-please[bot], …).
_ROUTINE_AUTHOR_RE = re.compile(r"\[bot\]$", re.IGNORECASE)

# Release/version-bump PRs authored by a human are still routine: they carry no design signal.
# Matches:
#   "chore: release v1.2.0"           — standard release-please output
#   "chore(main): release v1.2.0"     — release-please with branch scope
#   "chore(release): v0.7.0"          — manual release PR using scope=release
#   "chore: v0.7.0"                   — bare version bump commit
#
# NOTE: "chore(deps): upgrade frontend toolchain" is NOT routine when authored by a human —
# the scope is "deps" but the body is an intentional toolchain upgrade.  The distinction is
# enforced by the *bot-author* check above; this pattern only catches release/version titles.
_ROUTINE_HUMAN_TITLE_RE = re.compile(
    r"^chore(\([^)]*\))?\s*:\s*(release\b|v\d)", re.IGNORECASE
)

# Extracts the conventional-commit scope: "feat(frontend): …" → "frontend"
_CC_SCOPE_RE = re.compile(r"^[a-z]+\(([^)]+)\)", re.IGNORECASE)

# Extracts a short package name from "bump <pkg> from <ver> to <ver>" dependency-bump titles.
_DEP_BUMP_NAME_RE = re.compile(r"\bbump\s+([\w@./\-]+)\s+from\b", re.IGNORECASE)


def _is_routine_pr(pr: dict[str, object]) -> bool:
    """Return True if this PR carries little design signal (ROUTINE).

    ROUTINE:
    - Any bot-authored PR: author ``is_bot`` flag is True **or** login ends with ``[bot]``.
      (GitHub Apps like ``app/dependabot`` set ``is_bot=True``; classic ``dependabot[bot]``
      matches the login pattern — both are covered.)
    - Human-authored ``chore: release …`` PRs (auto-generated by release tooling).

    NOT routine (human-authored ``chore(deps)`` may be a deliberate toolchain upgrade):
    - PR titled ``chore(deps): upgrade frontend toolchain`` by a human → SUBSTANTIVE.
    """
    author_info = pr.get("author") or {}
    if isinstance(author_info, dict):
        # Prefer the explicit is_bot field present in gh CLI JSON responses.
        if author_info.get("is_bot") is True:
            return True
        login = str(author_info.get("login") or "")
    else:
        login = str(author_info)

    if _ROUTINE_AUTHOR_RE.search(login):
        return True

    title = str(pr.get("title") or "")
    return bool(_ROUTINE_HUMAN_TITLE_RE.match(title))


def _extract_cc_scope(title: str) -> str:
    """Return the conventional-commit scope from *title*, or ``''`` if absent.

    Examples::

        "feat(frontend): add dark mode"   → "frontend"
        "fix(auth): token expiry"         → "auth"
        "chore(deps): bump axios"         → "deps"
        "chore: release v1.0.0"           → ""
        "fix stale data in sidebar"       → ""
    """
    m = _CC_SCOPE_RE.match(title)
    return m.group(1).lower() if m else ""


def _extract_dep_name(title: str) -> str:
    """Extract a short package name from a dependency-bump PR title.

    ``"chore(deps): Bump axios from 0.21.1 to 0.21.4"``       → ``"axios"``
    ``"chore(deps-dev): Bump @types/react from 18.0 to 18.2"`` → ``"react"``

    Falls back to a trimmed fragment after the colon.
    """
    m = _DEP_BUMP_NAME_RE.search(title)
    if m:
        pkg = m.group(1)
        # "@scope/name" → "name" for brevity
        return pkg.split("/")[-1] if "/" in pkg else pkg
    if ":" in title:
        return title.split(":", 1)[-1].strip()[:30]
    return title[:30]


def _summarise_routine(routine_prs: list[dict[str, object]]) -> str:
    """Return a compact one-line aggregate description of routine (noise) PRs.

    Example output::

        "8 dependency bump(s) (form-data, dompurify, cryptography, ...); 2 release PR(s)"
    """
    dep_bumps: list[str] = []
    releases: int = 0

    for pr in routine_prs:
        title = str(pr.get("title") or "")
        if _ROUTINE_HUMAN_TITLE_RE.match(title):
            releases += 1
        else:
            dep_bumps.append(_extract_dep_name(title))

    fragments: list[str] = []
    if dep_bumps:
        # Show up to 6 unique package names; indicate truncation with "…"
        seen: list[str] = []
        for n in dep_bumps:
            if n and n not in seen:
                seen.append(n)
        shown = seen[:6]
        names_str = ", ".join(shown)
        if len(dep_bumps) > len(shown):
            names_str += ", ..."
        fragments.append(f"{len(dep_bumps)} dependency bump(s) ({names_str})")
    if releases:
        fragments.append(f"{releases} release PR(s)")
    if not fragments:
        fragments.append(f"{len(routine_prs)} routine PR(s)")

    return "; ".join(fragments)


def _append_pr_detail(parts: list[str], pr: dict[str, object]) -> None:
    """Append the full detail block for one substantive PR to *parts*."""
    n = pr.get("number", "?")
    title = pr.get("title") or "(no title)"
    raw_body = pr.get("body") or ""
    assert isinstance(raw_body, str)
    body_excerpt = (
        textwrap.shorten(raw_body.strip(), width=_PR_BODY_MAX, placeholder="\u2026")
        if raw_body.strip()
        else ""
    )
    author_info = pr.get("author") or {}
    if isinstance(author_info, dict):
        author_name = author_info.get("login") or "unknown"
    else:
        author_name = str(author_info)
    merged_at = str(pr.get("mergedAt") or "")[:10]
    files_list = pr.get("files") or []
    assert isinstance(files_list, list)
    file_count = len(files_list)
    top_paths = [str(f.get("path", "")) for f in files_list[:5] if isinstance(f, dict)]

    parts.append(f"### PR #{n}: {title}\n\n")
    parts.append(f"- **Author (PR opener):** {author_name}\n")
    parts.append(f"- **Merged:** {merged_at}\n")
    parts.append(f"- **Files changed:** {file_count}\n")
    if top_paths:
        parts.append(f"- **Key paths:** {', '.join(top_paths)}\n")
    if body_excerpt:
        parts.append(f"\n{body_excerpt}\n")
    parts.append("\n")


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def materialize(
    repo: str,
    since: str,
    until: str,
    max_prs: int = 15,
    max_modules: int = 5,
    repo_qualifier: Optional[str] = None,
) -> list[tuple[str, str]]:
    """Materialize source documents for the window (since, until].

    Args:
        repo:           Absolute path to the local git repository.
        since:          Window start date YYYY-MM-DD (exclusive — commits *after*
                        this date are included).
        until:          Window end date YYYY-MM-DD (inclusive, up to 23:59:59).
        max_prs:        Maximum merged PRs to include in the change digest.
        max_modules:    Maximum module snapshot documents to emit.
        repo_qualifier: When non-None (multi-repo mode) this short label is
                        injected into every filename and document body so that
                        sources from different repos never collide and citations
                        always trace back to the correct repo.  Typically the
                        repository's directory base-name (e.g.
                        ``"amplifier-app-team-pulse"``).
                        When None (single-repo mode) filenames are unqualified
                        — identical to historic behaviour.

    Returns:
        List of ``(filename, content)`` pairs ready to write into ``_inbox/``.
        Filenames are date-prefixed slugs as recommended by wiki-weaver.
    """
    origin_url = gitio.get_origin_url(repo)
    owner_repo: Optional[tuple[str, str]] = None
    if origin_url:
        owner_repo = gitio.parse_owner_repo(origin_url)

    until_rev = gitio.get_window_rev(repo, until)
    commits = gitio.get_commits_name_only(repo, since, until)

    docs: list[tuple[str, str]] = []

    # 1. Change digest
    # Filename: "<repo>-<until>-changes.md" (multi) or "<until>-changes.md" (single)
    digest_content = _build_change_digest(
        repo, since, until, until_rev, commits, owner_repo, max_prs, repo_qualifier
    )
    digest_filename = (
        f"{repo_qualifier}-{until}-changes.md"
        if repo_qualifier
        else f"{until}-changes.md"
    )
    docs.append((digest_filename, digest_content))

    # 2. Module snapshots
    # Filenames: "module-<repo>-<slug>-<until>.md" (multi) or "module-<slug>-<until>.md" (single)
    module_docs = _build_module_snapshots(
        repo, since, until, until_rev, commits, owner_repo, max_modules, repo_qualifier
    )
    docs.extend(module_docs)

    return docs


# ---------------------------------------------------------------------------
# Frontmatter helpers
# ---------------------------------------------------------------------------


def _frontmatter(author: str, source: str, date_str: str) -> str:
    """Emit YAML frontmatter block with only the fields that have values."""
    lines = ["---"]
    if author:
        lines.append(f"author: {author}")
    if source:
        lines.append(f"source: {source}")
    if date_str:
        lines.append(f"date: {date_str}")
    lines.append("---")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Change digest
# ---------------------------------------------------------------------------


def _build_change_digest(
    repo: str,
    since: str,
    until: str,
    until_rev: Optional[str],
    commits: list[dict[str, object]],
    owner_repo: Optional[tuple[str, str]],
    max_prs: int,
    repo_qualifier: Optional[str] = None,
) -> str:
    """Build the change-digest source document.

    In single-repo mode (``repo_qualifier=None``) the document title is
    ``# Changes: <since> -> <until>``.  In multi-repo mode a
    ``**Repository:** <qualifier>`` line is added immediately after the
    title so the synthesizer can attribute facts to the right repo and keep
    pages for different repos distinct.

    Merged PRs are split into two tiers so routine noise never buries real work:

    - **Substantive**: human-authored, non-release PRs.  Every one gets full
      detail (number, title, author, date, files, body excerpt) and is grouped
      by conventional-commit scope so coordinated same-area change-sets read
      together.  All substantive PRs within the fetched pool are shown.
    - **Routine**: bot-authored dependency bumps and auto-generated release PRs.
      Collapsed into a single compact line (counts + package names).  They do
      **not** consume the ``max_prs`` budget.

    The ``max_prs`` parameter controls how many PRs are fetched from GitHub
    (used as a scaling hint).  All substantive PRs within that fetched pool are
    shown; only routine ones are collapsed.
    """
    parts: list[str] = []
    parts.append(f"# Changes: {since} \u2192 {until}\n\n")
    # In multi-repo mode, label the repo so the synthesizer keeps digests distinct.
    if repo_qualifier:
        parts.append(f"**Repository:** `{repo_qualifier}`\n\n")

    # Fetch generously so the window is fully covered even when many newer PRs
    # exist beyond it.  Routine PRs are free (collapsed), so we never need to
    # trade one class against the other.
    fetch_cap = min(max(max_prs * 8, 80), 200)
    prs: list[dict[str, object]] = []
    if owner_repo:
        owner, name = owner_repo
        prs = gitio.gh_merged_prs(f"{owner}/{name}", since, until, max_fetch=fetch_cap)

    if prs:
        substantive: list[dict[str, object]] = [p for p in prs if not _is_routine_pr(p)]
        routine: list[dict[str, object]] = [p for p in prs if _is_routine_pr(p)]

        # ---- Substantive Changes ----
        parts.append("## Substantive Changes\n\n")
        if substantive:
            parts.append(
                "_Grouped by conventional-commit scope so coordinated change-sets "
                "read together. Routine dependency bumps and release PRs are "
                "collapsed in the section below — they do not consume this budget._\n\n"
            )
            # Group by CC scope; preserve the API's merged-at order within each group.
            scoped: dict[str, list[dict[str, object]]] = {}
            for pr in substantive:
                scope = _extract_cc_scope(str(pr.get("title") or ""))
                bucket = scope or "(general)"
                if bucket not in scoped:
                    scoped[bucket] = []
                scoped[bucket].append(pr)

            for scope_key, scope_prs in scoped.items():
                parts.append(f"### Area: `{scope_key}`\n\n")
                for pr in scope_prs:
                    _append_pr_detail(parts, pr)
        else:
            parts.append("_(No substantive PRs found in this window.)_\n\n")

        # ---- Routine Maintenance ----
        parts.append("## Routine Maintenance\n\n")
        if routine:
            summary = _summarise_routine(routine)
            parts.append(f"Routine maintenance this window: {summary}.\n\n")
        else:
            parts.append("_(None in this window.)_\n\n")

    else:
        parts.append(
            "## Merged Pull Requests\n\n"
            "_(None found in this window, or gh CLI unavailable.)_\n\n"
        )

    # ---- Commit-volume summary ----
    dir_counts: dict[str, int] = {}
    for commit in commits:
        paths_obj = commit.get("paths", [])
        assert isinstance(paths_obj, list)
        seen_dirs: set[str] = set()
        for p in paths_obj:
            assert isinstance(p, str)
            parts_path = p.split("/")
            top_dir = parts_path[0] if len(parts_path) > 1 else "(root)"
            if top_dir not in seen_dirs:
                dir_counts[top_dir] = dir_counts.get(top_dir, 0) + 1
                seen_dirs.add(top_dir)

    total_commits = len(commits)
    parts.append(
        f"## Commit Volume Summary ({since} \u2192 {until})\n\n"
        f"Total commits in window: {total_commits}\n\n"
    )
    if dir_counts:
        parts.append("Commits by top-level directory:\n\n")
        for d, count in sorted(dir_counts.items(), key=lambda x: -x[1]):
            parts.append(f"- `{d}`: {count} commit(s)\n")
        parts.append("\n")

    # ---- Window contributors (provenance, NOT per-PR authorship) ----
    # Appended to the body BEFORE the frontmatter is composed so the section
    # is clearly visible in the document — and explicitly NOT the PR-opener field.
    authors = gitio.get_shortlog_authors(repo, since, until, top_n=3)
    if authors:
        parts.append("## Window Contributors\n\n")
        parts.append(
            "_Git-log contributors in this window (window-level provenance — "
            "NOT the per-PR opener; see each PR's `Author (PR opener)` field "
            "for authoritative per-PR attribution.)_\n\n"
        )
        parts.append(", ".join(authors) + "\n\n")

    # ---- Frontmatter ----
    # Use only the single top contributor so the `author:` metadata field cannot
    # be mistaken for a list of PR authors by downstream synthesizers.
    fm_author = authors[0] if authors else ""
    source_url = ""
    if owner_repo:
        owner, name = owner_repo
        source_url = f"https://github.com/{owner}/{name}/pulls?q=is:pr+is:merged"

    fm = _frontmatter(fm_author, source_url, until)
    return fm + "\n\n" + "".join(parts)


# ---------------------------------------------------------------------------
# Module snapshots
# ---------------------------------------------------------------------------


def _slug(name: str) -> str:
    """Convert a directory name to a filesystem-safe slug."""
    return name.lower().replace("/", "-").replace("_", "-").replace(" ", "-").strip("-")


def _rank_modules(commits: list[dict[str, object]]) -> list[tuple[str, int]]:
    """Rank top-level directories by the number of commits that touched them.

    Root-level files (no directory component) are excluded since they are
    typically tooling files (pyproject.toml, README.md, etc.) rather than
    substantive code modules.
    """
    dir_counts: dict[str, int] = {}
    for commit in commits:
        paths_obj = commit.get("paths", [])
        assert isinstance(paths_obj, list)
        seen: set[str] = set()
        for p in paths_obj:
            assert isinstance(p, str)
            parts = p.split("/")
            if len(parts) < 2:
                continue  # root-level file — skip
            top_dir = parts[0]
            if top_dir not in seen:
                dir_counts[top_dir] = dir_counts.get(top_dir, 0) + 1
                seen.add(top_dir)
    return sorted(dir_counts.items(), key=lambda x: -x[1])


def _build_module_snapshots(
    repo: str,
    since: str,
    until: str,
    until_rev: Optional[str],
    commits: list[dict[str, object]],
    owner_repo: Optional[tuple[str, str]],
    max_modules: int,
    repo_qualifier: Optional[str] = None,
) -> list[tuple[str, str]]:
    ranked = _rank_modules(commits)[:max_modules]
    results: list[tuple[str, str]] = []
    for module_path, commit_count in ranked:
        content = _build_module_doc(
            repo,
            since,
            until,
            until_rev,
            module_path,
            commit_count,
            commits,
            owner_repo,
            repo_qualifier,
        )
        if content:
            # Multi-repo: "module-<repo>-<slug>-<until>.md"  (non-colliding)
            # Single-repo: "module-<slug>-<until>.md"         (historic, unchanged)
            if repo_qualifier:
                filename = f"module-{repo_qualifier}-{_slug(module_path)}-{until}.md"
            else:
                filename = f"module-{_slug(module_path)}-{until}.md"
            results.append((filename, content))
    return results


def _extract_readme_purpose(content: str) -> str:
    """Extract the first prose paragraph from a README, skipping the title."""
    lines = content.splitlines()
    para: list[str] = []
    past_title = False

    for line in lines:
        stripped = line.strip()
        if not past_title:
            if stripped.startswith("#"):
                past_title = True
            elif stripped:
                # No title found; treat first line as content
                past_title = True
                para.append(stripped)
            continue
        # After the title
        if not stripped:
            if para:
                break  # end of first paragraph
        else:
            # Skip lines that look like badges, shields, HTML tags
            if stripped.startswith("[![") or stripped.startswith("<"):
                continue
            para.append(stripped)

    result = " ".join(para).strip()
    if not result:
        return ""
    return textwrap.shorten(result, width=500, placeholder="\u2026")


def _build_module_doc(
    repo: str,
    since: str,
    until: str,
    until_rev: Optional[str],
    module_path: str,
    commit_count: int,
    all_commits: list[dict[str, object]],
    owner_repo: Optional[tuple[str, str]],
    repo_qualifier: Optional[str] = None,
) -> Optional[str]:
    """Build a single module snapshot document.

    In multi-repo mode (``repo_qualifier`` set) the title becomes
    ``# Module: <path> (<repo>)`` and a **Repository** line is injected
    so the synthesizer treats modules with the same path but different repos
    as distinct pages rather than merging them.
    """
    parts: list[str] = []
    if repo_qualifier:
        # Disambiguate: "frontend (amplifier-app-team-pulse)" vs "frontend (amplifier-bundle-wiki-weaver)"
        parts.append(f"# Module: {module_path} ({repo_qualifier})\n\n")
        parts.append(f"**Repository:** `{repo_qualifier}`\n\n")
    else:
        parts.append(f"# Module: {module_path}\n\n")

    # ---- Purpose ----
    purpose: Optional[str] = None
    if until_rev:
        for readme_name in _README_CANDIDATES:
            raw = gitio.get_file_at_rev(repo, until_rev, f"{module_path}/{readme_name}")
            if raw:
                purpose = _extract_readme_purpose(raw)
                break

    if purpose:
        parts.append(f"## Purpose\n\n{purpose}\n\n")
    else:
        # Derive purpose from the directory name — mark clearly as inferred
        inferred = (
            f"_(Inferred — no README found for `{module_path}`.)_ "
            f"The `{module_path}` directory contains source files for this "
            f"area of the repository."
        )
        parts.append(f"## Purpose\n\n{inferred}\n\n")

    # ---- File inventory ----
    if until_rev:
        files = gitio.get_tree_at_rev(repo, until_rev, module_path)
        if files:
            rev_short = until_rev[:8]
            parts.append(f"## File Inventory (at {rev_short})\n\n")
            shown = files[:_MAX_INVENTORY_FILES]
            for f in shown:
                parts.append(f"- `{f}`\n")
            if len(files) > _MAX_INVENTORY_FILES:
                extra = len(files) - _MAX_INVENTORY_FILES
                parts.append(f"- _(\u2026 and {extra} more files)_\n")
            parts.append("\n")

    # ---- What changed this window ----
    touching: list[dict[str, object]] = []
    prefix = module_path + "/"
    for c in all_commits:
        paths_obj = c.get("paths", [])
        assert isinstance(paths_obj, list)
        if any(
            (isinstance(p, str) and (p.startswith(prefix) or p == module_path))
            for p in paths_obj
        ):
            touching.append(c)

    parts.append(f"## Changes This Window ({since} \u2192 {until})\n\n")
    parts.append(f"{commit_count} commit(s) touched this module in this window.\n\n")
    if touching:
        for c in touching[:12]:
            h = str(c.get("hash", ""))[:8]
            subj = str(c.get("subject", ""))
            parts.append(f"- `{h}` {subj}\n")
        if len(touching) > 12:
            parts.append(f"- _(\u2026 and {len(touching) - 12} more)_\n")
    parts.append("\n")

    # ---- Top contributors this window (provenance, NOT authorship of any PR) ----
    # Listed in the body with an explicit label so it is never confused with
    # a per-PR `Author (PR opener)` field.
    authors = gitio.get_shortlog_authors(repo, since, until, path=module_path, top_n=3)
    if authors:
        parts.append("## Top Contributors This Window\n\n")
        parts.append(
            f"_Committers to `{module_path}` in this window "
            f"(window-level provenance — NOT the PR opener; "
            f"see the change-digest for per-PR attribution):_\n\n"
        )
        parts.append(", ".join(authors) + "\n\n")

    # ---- Frontmatter ----
    # Single top contributor keeps the `author:` metadata unambiguous;
    # the full list is in the body section above.
    fm_author = authors[0] if authors else ""
    source_url = ""
    if owner_repo and until_rev:
        owner, name = owner_repo
        rev_short = until_rev[:8]
        source_url = f"https://github.com/{owner}/{name}/tree/{rev_short}/{module_path}"

    fm = _frontmatter(fm_author, source_url, until)
    return fm + "\n\n" + "".join(parts)
